version: "3"
services:
  app:
    build: ./app
    ports:
      - 80:80

  admin:
    build: ./admin
    privileged: true
    ports:
      - 8000:8000
    environment:
      - FLAG=SEE{REDACTED}
      - UUID=REDACTED